name: Feature request
description: Suggest an improvement or new feature
title: "[Feature] "
labels: []
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to add?
      description: Describe the feature.
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why would it be useful?
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Additional ideas
